<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vaishnavi" failures="1" tests="3" name="Error Validations Test" time="60.911" errors="0" timestamp="2025-01-09T01:22:08 IST">
  <testcase classname="rahulshettyacademy.tests.ErrorValidationsTest" name="loginErrorvalidation" time="1.239"/>
  <testcase classname="rahulshettyacademy.tests.ErrorValidationsTest" name="productErrorValidation" time="25.079">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="rahulshettyacademy.tests.ErrorValidationsTest" name="productErrorValidation" time="14.86">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rahulshettyacademy.tests.ErrorValidationsTest.productErrorValidation(ErrorValidationsTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validations Test -->
